# Generated by Django 4.1.13 on 2024-05-13 18:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jewelary",
            name="merchat",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
