# Generated by Django 4.1.13 on 2024-05-13 18:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_jewelary_merchat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jewelary",
            name="merchat",
            field=models.ManyToManyField(
                related_name="merchats", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
